// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateActivity(arg1) {
  return window['go']['main']['App']['CreateActivity'](arg1);
}

export function DeleteActivity(arg1) {
  return window['go']['main']['App']['DeleteActivity'](arg1);
}

export function GetActivities() {
  return window['go']['main']['App']['GetActivities']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
