// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateActivity(arg1:main.Activity):Promise<void>;

export function DeleteActivity(arg1:string):Promise<void>;

export function GetActivities():Promise<Array<main.Activity>>;

export function Greet(arg1:string):Promise<string>;
